### ISSUE TITLE
Could you include ipget in some official IPFS docker image?

### ISSUE THREAD

**Issue by Ark-kun** [ipfs/ipget#102]
I thought I'd find the tool in [ipfs/go-ipfs](https://hub.docker.com/r/ipfs/go-ipfs), but it wasn't there.

**Comment by guseggert** [comment]
We can't commit to maintaining a Docker image for this. Feel free to make one yourself, you can grab the binary from https://dist.ipfs.tech/#ipget.

**Comment by Ark-kun** [comment]
I'm not asking to make a separate image for just ipget. But I think the expectations of the [ipfs/go-ipfs](https://hub.docker.com/r/ipfs/go-ipfs) users might be that ipget is included.
