### ISSUE TITLE
How and where do I run "$ go install github.com/ipfs/ipget@latest"

### ISSUE THREAD

**Issue by willow0217** [ipfs/ipget#148]
Hi, I'm new to all of this stuff.
I've read the instructions on how to install ipget, but I do not understand how and where do I run `$ go install github.com/ipfs/ipget@latest`. I've tried to run it in powershell and also using command prompt, but it doesn't work and I'm pretty sure I'm not supposed to run it there, but I also have no idea where else I'm supposed to run it.
My operating system is windows, so I can't use brew. I tried chocolatey but it's not in their sources. 
I also don't understand how and where I'm supposed to run commands like `$ ipget QmQ2r6iMNpky5f1m4cnm3Yqw8VSvjuKpTcK1X7dBR1LkJF/cat.gif -o nyan.gif` if I do get ipget installed. 
I have already downloaded a zip file from [IPFS Distributions](https://dist.ipfs.io/#ipget), it contains a file names Install and another named ipget and I tried running both but nothing happens. 
If someone knows, please help. 
Thank you.

**Comment by Stebalien** [comment]
I highly suggest you install something like [ipfs-desktop](https://docs.ipfs.tech/install/ipfs-desktop/) instead. This is a command-line tool and expects general familiarity with the command-line.

However, here are a couple of suggestions:

1. Remove the leading `$ `. That just indicates "this is a command" for documentation purposes. I.e., you'll want to run `go install ...`, not `$ go install ...`.
2. You'll need the go toolchain installed for this to work.
3. You should be able to invoke these tools from ether CMD or PowerShell.

Unfortunately, that's really all the help I can give you here.
