### ISSUE TITLE
Tests + TravisCI

### ISSUE THREAD

**Issue by noffle** [ipfs/ipget#2]
- [x] travis github integration
- [x] basic test coverage using [sharness](https://github.com/mlafeldt/sharness)
- [x] test against local node and fallback ephemeral node separately

**Comment by lidel** [comment]
If you want to run tests automatically on each push / pull request with as little effort as possible, you can use TravisCI. It can be set up to report test coverage to the Coveralls site.

I use both with a [simple IRC bot in Golang](https://github.com/lidel/meowkov).
Configuration is very simple: 
- https://github.com/lidel/meowkov/blob/master/.travis.yml

Results:
- https://travis-ci.org/lidel/meowkov
- https://coveralls.io/github/lidel/meowkov?branch=master

**Comment by noffle** [comment]
Thanks! I'll get this rigged up once there are some tests to run.

**Comment by noffle** [comment]
Basic Travis integration is done! Now to get some [sharness](https://github.com/mlafeldt/sharness) tests in!

**Comment by noffle** [comment]
Basic coverage: https://github.com/ipfs/ipget/pull/35

Still needed: test against local node and fallback ephemeral node separately

**Comment by noffle** [comment]
Woohoo!
