### ISSUE TITLE
nicer help?

### ISSUE THREAD

**Issue by jbenet** [ipfs/ipget#20]
help should have a description of what this tool is used for, and an example. look at the man pages for wget and curl. so instead of:

```
Retrieve and save IPFS objects.
```
maybe:

```
ipget - retrieve and save IPFS objects

ipget is a tool for non-interactive downloading of files or objects from IPFS to the 
user's filesystem, similar to wget or curl. It supports /ipfs and /ipns paths. ipget
is meant to be used in scripts and pipelines.
```
or something.

**Comment by noffle** [comment]
I think you're right that `ipget` should have a stellar `man` page, like `wget` and `curl`.

I think we can do better than their usage output though -- theirs is very terse:

wget
```
stephen // ~ $ wget
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
```

curl:
```
stephen // ~ $ curl
curl: try 'curl --help' or 'curl --manual' for more information
```

We shouldn't mimick blindly here. I think something that offers a description like you said and common options is better usage output. This can be complemented with excellent `man` pages.

Let's **not** copy these tools' `--help` output though (check it out; it's a massive many-page dump).

---

Summary:
- [ ] usage output that describes the tool's use, provides an example, and describes usage
- [ ] a great `man` page that gives background on IPFS, what multiaddresses are, includes full step-by-step examples, and any other context a brand new user would need to understand the tool (`curl --manual` does a great job; talks about what URLs are, etc)
- [ ] should offer hooks throughout that invite the user to learn more about IPFS; act as a *gateway* into the IPFS community / suite of tools

**Comment by noffle** [comment]
Broke these out into #45 and #46.
