### ISSUE TITLE
Feature idea: --seed

### ISSUE THREAD

**Issue by noffle** [ipfs/ipget#28]
It might be nice to be able to run

```
$ ipget /ipfs/Qmfoobar --seed
```

and have `ipget` hang on completion, keeping the data around and available to the network.

**Comment by hsanjuan** [comment]
This is incompatible with running in client mode and it crosses the line between being just a client or a full daemon. I am per-preemptively closing as it means re-implementing functionality which exists in go-ipfs anyways. If anyone has true interest in this, or a maintainer wants to do it, please re-open.
