### ISSUE TITLE
Ensure example hashes are always available

### ISSUE THREAD

**Issue by noffle** [ipfs/ipget#33]
The README refers to a delightful cat gif, `QmQ2r6iMNpky5f1m4cnm3Yqw8VSvjuKpTcK1X7dBR1LkJF`. It would be nice if we made sure it was pinned on Solar (if it isn't already) so that when people try the example it works.

The other challenge is ensuring the IPNS example continues to work. I'm not sure what options exist for keeping an IPNS entry fresh in Solar indefinitely is -- @lgierth?

**Comment by hsanjuan** [comment]
It is pinned. I'll let the readme mention that the other does not work.
