### ISSUE TITLE
SIGINT doesn't interrupt the embeded node

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/ipget#34]
```
./ipget QmRrPRCRT3KEkQVBoA2f6X2jpbBEV7vgypbYJpVaoag4ia                               
^C^C^C^C^C^C^C^C^C^C^C^C^C
```

**Comment by noffle** [comment]
Good catch, @Kubuxu. We need a way to provide https://github.com/noffle/fallback-ipfs-shell/ with a context so we can nix it from the outside. I'll add this to 1.0.0.

**Comment by noffle** [comment]
You know, we could probably just `os.Exit(1)` without doing damage, since it's either hanging on a connection to a local daemon OR an ephemeral node it spun up. It'd be ideal to close cleanly, but for 1.0.0 this'd probably be fine.

**Comment by noffle** [comment]
Filed https://github.com/ipfs/ipget/issues/39 for making improvements to this.
