### ISSUE TITLE
Clean cli termination

### ISSUE THREAD

**Issue by noffle** [ipfs/ipget#39]
Right now sending SIGTERM or SIGINT to ipget results in the process being [exited immediately](https://github.com/ipfs/ipget/issues/37), with no clean up. We should have [fallback-ipfs-shell](https://github.com/noffle/fallback-ipfs-shell/)'s API methods accept a `Context` that lets us cancel the shell(s) at the ipget level once a termination signal is encountered.

**Comment by gammazero** [comment]
Fixed in #84
