### ISSUE TITLE
Fallback to ephemeral shell on "get" failure, too

### ISSUE THREAD

**Issue by noffle** [ipfs/ipget#42]
Right now `ipget` tries to connect to a local IPFS node and does a `get` on the desired hash. If connecting to the local node fails, an ephemeral node is spawned. However, if the local node is connected to successfully _but_ the `get` fails due to the hash not being found, the code doesn't fall back to creating an ephemeral node.

This is usually fine, since the local node is generally connected to the Solar bootstrap nodes. However, in cases like ipfs running in `--offline` mode, this won't be true. What is the expected behaviour?

**Comment by hsanjuan** [comment]
As long as the process is verbose (#43) it should be clear enough why things fail in this case (which I'd say it is not a default user journey). Since this is old and no feedback was given, and it is not actionable, I am closing.
