### ISSUE TITLE
manual

### ISSUE THREAD

**Issue by noffle** [ipfs/ipget#45]
`wget` and `curl` do a great job in most regards. To be invoked on `man ipget` or `ipget --manual`:
- [ ] a great `man` page that gives background on IPFS, what multiaddresses are, includes full step-by-step examples, and any other context a brand new user would need to understand the tool (`curl --manual` does a great job; talks about what URLs are, etc)
- [ ] should offer hooks throughout that invite the user to learn more about IPFS; act as a _gateway_ into the IPFS community / suite of tools

**Comment by hsanjuan** [comment]
I am closing this as this would mean duplicating documentation which we are trying to centralize in the docs site. The ipget tool itself as a CLI tool should self-document, but that's it.
