### ISSUE TITLE
Timeout fetching dependencies

### ISSUE THREAD

**Issue by iainnicol** [ipfs/ipget#48]
I am unable to build with `make install`.  It seems to time out fetching the dependencies.  I am new to IPFS, so it's possible of course that the fault may lie in another component.

```shell
bin/gx-v0.11.0 --verbose install --global
installing package: ipget-0.2.5
  - Qmdk8Ea9GkbwHr7UNKVYaLRwwHSt69xBXuSvRVyNWZ9sZE not found locally, fetching into /home/iain/programming/gopath/src/gx/ipfs/Qmdk8Ea9GkbwHr7UNKVYaLRwwHSt69xBXuSvRVyNWZ9sZE
  - fetching Qmdk8Ea9GkbwHr7UNKVYaLRwwHSt69xBXuSvRVyNWZ9sZE via ipfs api
  - fetch finished in 1.063073511s
  - fetch Qmdk8Ea9GkbwHr7UNKVYaLRwwHSt69xBXuSvRVyNWZ9sZE complete!
[1 / 1] fetched dep: fallback-ipfs-shell
successfully found all deps for ipget
  - ipget depends on fallback-ipfs-shell (Qmdk8Ea9GkbwHr7UNKVYaLRwwHSt69xBXuSvRVyNWZ9sZE)
installing package: fallback-ipfs-shell-3.2.4
  - QmSWLfmj5frN9xVLMMN846dMDriy5wN5jeghUm7aTW3DAG not found locally, fetching into /home/iain/programming/gopath/src/gx/ipfs/QmSWLfmj5frN9xVLMMN846dMDriy5wN5jeghUm7aTW3DAG
  - QmQ1TuGrcSXjsGXEhdWPJTyfkrgMHCu2pcENRxgHQQ59wL not found locally, fetching into /home/iain/programming/gopath/src/gx/ipfs/QmQ1TuGrcSXjsGXEhdWPJTyfkrgMHCu2pcENRxgHQQ59wL
  - fetching QmSWLfmj5frN9xVLMMN846dMDriy5wN5jeghUm7aTW3DAG via ipfs api
  - fetching QmQ1TuGrcSXjsGXEhdWPJTyfkrgMHCu2pcENRxgHQQ59wL via ipfs api
  - QmdidTt1eZtEAn1Qv1rF9kHPusm57RkfNnsZsrQndsm8TT not found locally, fetching into /home/iain/programming/gopath/src/gx/ipfs/QmdidTt1eZtEAn1Qv1rF9kHPusm57RkfNnsZsrQndsm8TT
  - fetching QmdidTt1eZtEAn1Qv1rF9kHPusm57RkfNnsZsrQndsm8TT via ipfs api
  - fetch finished in 435.753791ms
  - fetch QmSWLfmj5frN9xVLMMN846dMDriy5wN5jeghUm7aTW3DAG complete!
[1 / 3] fetched dep: go-multiaddr
  - fetch finished in 521.122854ms
  - fetch QmdidTt1eZtEAn1Qv1rF9kHPusm57RkfNnsZsrQndsm8TT complete!
[2 / 3] fetched dep: go-ipfs-api
ERROR: from shell.Get(): Post http://v04x.ipfs.io/api/v0/get?arg=QmQ1TuGrcSXjsGXEhdWPJTyfkrgMHCu2pcENRxgHQQ59wL&encoding=json&stream-channels=true: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
retrying fetch QmQ1TuGrcSXjsGXEhdWPJTyfkrgMHCu2pcENRxgHQQ59wL after a second...

```

**Comment by lgierth** [comment]
Someone forgot to pin QmQ1TuGrcSXjsGXEhdWPJTyfkrgMHCu2pcENRxgHQQ59wL

**Comment by djdv** [comment]
This is a big deal, it's (still) impossible to build this tool.

**Comment by noffle** [comment]
This project needs a maintainer!

**Comment by lidel** [comment]
Tracked missing dependency: ipget → fallback-ipfs-shell →  ipfs-embedded-shell

@whyrusleeping any chance you got [ipfs-embedded-shell v0.1.0](https://github.com/whyrusleeping/ipfs-embedded-shell/blob/master/.gx/lastpubver) stashed on offline node somewhere? 
If not, can you re-release it as v0.1.1?

**Comment by whyrusleeping** [comment]
Doesnt look like I have it pinned. Let me see if i can recreate it

**Comment by whyrusleeping** [comment]
@lidel heres the new hash: QmcbLLZJa9oXnYTZWfS4T16n8B2mHFZkAzkKBNdGVzgG8g

**Comment by lidel** [comment]
Thanks! @noffle do you mind adding me as a collaborator to https://github.com/noffle/fallback-ipfs-shell ? 
To finalize fix we need to bump deps there and make a new release.

**Comment by noffle** [comment]
@lidel done! thanks y'all for taking such quick awesome action :heart:

**Comment by djdv** [comment]
@whyrusleeping 
I don't know where else to comment on this, but would it be worth hosting source releases on dist.ipfs.io? They could have gx deps vendored already or something like that.

**Comment by whyrusleeping** [comment]
@djdv we do pin all the dependencies on the same infrastructure as dist.ipfs.io. If anything isnt accessible, then it should be brought to our attention so we can pin it there.

**Comment by djdv** [comment]
@whyrusleeping 
Sorry, I meant like a tar style archive, something that contains the source in a state where building is basically guaranteed. In this case a release that had all the dependencies vendored in a way that allowed you to basically reproduce the release binary of the same version, if that makes sense.

**Comment by whyrusleeping** [comment]
Oh yeah, thats a great idea. We should add that as a step to our distibutions build script.
