### ISSUE TITLE
Go get fails with unrecognized import path

### ISSUE THREAD

**Issue by montanaflynn** [ipfs/ipget#49]
Following https://github.com/ipfs/ipget#install-from-source on a mac:

```
go get -d github.com/ipfs/ipget
package gx/ipfs/QmQa2wf1sLFKkjHCVEbna8y5qhdMjL8vtTJSAc48vZGTer/go-ipfs/path: unrecognized import path "gx/ipfs/QmQa2wf1sLFKkjHCVEbna8y5qhdMjL8vtTJSAc48vZGTer/go-ipfs/path" (import path does not begin with hostname)
package gx/ipfs/QmVcLF2CgjQb5BWmYFWsDfxDjbzBfcChfdHRedxeL3dV4K/cli: unrecognized import path "gx/ipfs/QmVcLF2CgjQb5BWmYFWsDfxDjbzBfcChfdHRedxeL3dV4K/cli" (import path does not begin with hostname)
package gx/ipfs/Qmdk8Ea9GkbwHr7UNKVYaLRwwHSt69xBXuSvRVyNWZ9sZE/fallback-ipfs-shell: unrecognized import path "gx/ipfs/Qmdk8Ea9GkbwHr7UNKVYaLRwwHSt69xBXuSvRVyNWZ9sZE/fallback-ipfs-shell" (import path does not begin with hostname)
```

**Comment by doyzfly** [comment]
me too

**Comment by LastExile16** [comment]
I also have the same problem. any fix please?

**Comment by lanzafame** [comment]
@montanaflynn @doyzfly @LastExile16 this is an expected error as imports in `ipget` are specified with the hash produced by the [`gx`](https://github.com/whyrusleeping/gx) tool. Follow the instructions to [install from source](https://github.com/ipfs/ipget#install-from-source).

**Comment by montanaflynn** [comment]
@lanzafame that should probably be documented on the page, otherwise users like me will think it's broken and not continue onto the next steps.

**Comment by gammazero** [comment]
The gx tool is no longer used, so this problem is not happening anymore.
