### ISSUE TITLE
`temp` sets up plugins in default path but then it calls tmpNode which creates another ephemeral repo

### ISSUE THREAD

**Issue by daviddias** [ipfs/ipget#67]
https://github.com/ipfs/ipget/blob/70497d76183e7d702b00c9b2fc77d9e3fdf50049/node.go#L77-L89 sets the plugins on the defaultPath, but then calls tempNode that goes on and creates a repo on a new temporary directory https://github.com/ipfs/ipget/blob/70497d76183e7d702b00c9b2fc77d9e3fdf50049/node.go#L92. 

Doesn't seem right, but I be missing a goism or two :)

**Comment by Stebalien** [comment]
Yeah, this is funky. It's _loading_ the plugins from the default repo because there aren't going to be any in the temp repo. Honestly, it doesn't really need to load _any_ plugins from disk.

However, it doesn't really _hurt_ to try to load the user's plugins.
