### ISSUE TITLE
ipget automatically saving and exiting session upon opening program, unable to input any commands

### ISSUE THREAD

**Issue by YeOldGit** [ipfs/ipget#95]

**Comment by YeOldGit** [comment]
<img width="583" alt="Screen Shot 2021-09-16 at 10 00 13 AM" src="https://user-images.githubusercontent.com/90860953/133654684-7b44bbe2-ee09-4697-b216-a496a99d9dd4.png">

**Comment by YeOldGit** [comment]
I don't think my writeup got saved when creating the issue. 

I have ipget on a Mac and as soon as I open the program, it automatically posts the above process and freezes the window so no commands can be input. How do I prevent or bypass this issue? Thanks in advance!

**Comment by Stebalien** [comment]
`ipget` is a command line tool. You need to execute it from a terminal, not by double clicking on the executable. You probably want https://docs.ipfs.io/install/ipfs-desktop/.
